state_bucket_name   = "fruit-api-state-bucket"
dynamodb_table_name = "fruit-api-lock-table"
lambda_code_bucket  = "fruit-api-lambda-code-bucket"
backend_db_hash_key = "LockID"
repository          = "dtolbertcooke/Portfolio-Project-2"